import type { Metadata } from "next";
import { Antonio } from "next/font/google";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import Container from "@/blocks/elements/container/Container";
import ClickSpark from "@/blocks/elements/3d/ClickSpark/ClickSpark";
import LiquidScrollTop from "@/blocks/elements/3d/LiquidScrollTop/LiquidScrollTop";
import PageLoadLoader from "@/blocks/elements/3d/PageLoadLoader/PageLoadLoader";
import { PageLoadLoaderProvider } from "@/blocks/elements/3d/PageLoadLoader/functions";
import PageLoadGate from "@/blocks/elements/3d/PageLoadLoader/PageLoadGate";
import TargetCursor from "@/blocks/elements/3d/TargetCursor/TargetCursor";
import BubbleMenu from "@/blocks/elements/3d/BubbleMenu/BubbleMenu";
import { defaultItems } from "@/blocks/elements/3d/BubbleMenu/functions";
import HeraBanner from "@/blocks/sections/frontend/heroBanner/HeroBanner";
import SectionScrollSnap from "@/blocks/elements/3d/SectionScrollSnap/SectionScrollSnap";
import { ParallaxRoot } from "@/hooks/parallax";

const antonio = Antonio({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-antonio",
});

const openSans = Open_Sans({
  weight: ["400", "600", "700"],
  subsets: ["latin"],
  variable: "--font-open-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${antonio.variable} ${openSans.variable} ${openSans.className} antialiased`}
      >
        <SectionScrollSnap />
        <PageLoadLoaderProvider>
        <PageLoadGate />
        <ParallaxRoot>
        <TargetCursor
          spinDuration={2}
          hideDefaultCursor
          parallaxOn
          hoverDuration={0.2}
        />
        <ClickSpark
          sparkColor='#fff'
          sparkSize={10}
          sparkRadius={25}
          sparkCount={8}
          duration={400}
        >
        <BubbleMenu
          items={defaultItems}
          menuAriaLabel="Toggle navigation"
          menuBg="var(--primary)"
          menuContentColor="var(--secondary)"
          useFixedPosition={true}
          animationEase="back.out(1.5)"
          animationDuration={0.5}
          staggerDelay={0.12}
        />
        <LiquidScrollTop />

          <Container
            as="div"
            className="flex flex-col gap-0 overflow-x-clip overflow-y-visible"
          >
            <HeraBanner />
            {children}
          </Container>
          <PageLoadLoader />
        </ClickSpark>
        </ParallaxRoot>
        </PageLoadLoaderProvider>
      </body>
    </html>
  );
}
