import type { Metadata } from "next";
import { Antonio } from "next/font/google";
import { Open_Sans } from "next/font/google";
import "./globals.css";

const antonio = Antonio({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-antonio",
});

const openSans = Open_Sans({
  weight: ["400", "600", "700"],
  subsets: ["latin"],
  variable: "--font-open-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${antonio.variable} ${openSans.variable} ${openSans.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
